### ISSUE TITLE
database.php

### ISSUE THREAD

**Issue by yuya-matsushima** [Ryota-KM/farmer_cms#1]
## ファイルがない

`database.php` はおそらく DB 接続用の定数が定義されているファイルだと思います。パスワード等の情報が記載されているため commit していないと思われますが, こういう場合は `database.php.sample` のようなファイルを用意し, 同内容でパスワード等を適当なダミーにしたものを用意した方がいいです。

## edit-desc.php

database.php が 4 回　require_once されていますが、そんなに必要???

**Comment by ryokym** [comment]
ありがとうございます。
アドバイス通り、ダミーのファイルを用意しました。
あと仰る通りdatabase.phpのrequire_onceは1回で十分過ぎました。

**Comment by yuya-matsushima** [comment]
github は コミットメッセージに `fix #{num}` みたいにすると issue が close するから使うといいですよ。

https://qiita.com/maeda_t/items/d9ef98bf651bd491b16d
