### ISSUE TITLE
DB の dump ファイル

### ISSUE THREAD

**Issue by yuya-matsushima** [Ryota-KM/farmer_cms#3]
この cms で利用している DB の table の状態が不明です。phpmyadmin や sequel pro あたりで dump を作成すると良さそう。

注意: ID, PASSWORD の類は適当な値に書き換える必要があります。

**Comment by ryokym** [comment]
ありがとうございます。
アドバイス頂いた通りファイルを作成しました。

**Comment by yuya-matsushima** [comment]
dump ファイルおかしいですよ？せっかく作ってるんですから、自分で追加しているファイルの内容は確認するようにした方がいいですよ。

- \`customer\` のような SQL のコメントでもない変な文字が含まれてる
- AUTO_INCREMENT の値が 1 じゃない
